/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DigitGraphics40.c                                     *
* Font:        01 DigitGraphics                                      *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  32                                           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDigitGraphics40;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0021[ 24] = { /* code 0021, EXCLAMATION MARK */
  _XX_____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XX_____,
  ________,
  ________,
  _XX_____,
  XXXX____,
  XXXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0022[ 18] = { /* code 0022, QUOTATION MARK */
  _XX_____,_XX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XX_____,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0023[100] = { /* code 0023, NUMBER SIGN */
  _______X,X_______,XX______,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  ______XX,XX_____X,XXX_____,________,
  _______X,X_______,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0024[ 72] = { /* code 0024, DOLLAR SIGN */
  ________,___XX___,________,
  ________,__XXXX__,________,
  ____XXXX,XXXXXXXX,XXXXXXX_,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXX___,__XXXX__,________,
  XXXX____,__XXXX__,________,
  XXXX____,__XXXX__,________,
  XXXXXX__,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXXXX_,
  _____XXX,XXXXXXXX,XXXXXXX_,
  ________,__XXXX__,___XXXXX,
  ________,__XXXX__,____XXXX,
  ________,__XXXX__,____XXXX,
  ________,__XXXX__,___XXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,__XXXX__,________,
  ________,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0025[ 75] = { /* code 0025, PERCENT SIGN */
  ________,________,_____XX_,
  ________,________,____XXXX,
  ________,________,___XXXXX,
  ___XXXX_,________,__XXXXXX,
  __XXXXXX,________,_XXXXXX_,
  __XXXXXX,________,XXXXXX__,
  __XXXXXX,_______X,XXXXX___,
  __XXXXXX,______XX,XXXX____,
  ___XXXX_,_____XXX,XXX_____,
  ________,____XXXX,XX______,
  ________,___XXXXX,X_______,
  ________,__XXXXXX,________,
  ________,_XXXXXX_,________,
  ________,XXXXXX__,________,
  _______X,XXXXX___,________,
  ______XX,XXXX____,________,
  _____XXX,XXX_____,________,
  ____XXXX,XX______,_XXXX___,
  ___XXXXX,X_______,XXXXXX__,
  __XXXXXX,________,XXXXXX__,
  _XXXXXX_,________,XXXXXX__,
  XXXXXX__,________,XXXXXX__,
  XXXXX___,________,_XXXX___,
  XXXX____,________,________,
  _XX_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0026[ 66] = { /* code 0026, AMPERSAND */
  ____XXXX,XXXXXX__,________,
  __XXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,X_______,
  XXXXX___,_____XXX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,_______X,X_______,
  XXXXX___,________,________,
  _XXXXX__,________,________,
  _XXXXXX_,________,________,
  ___XXXXX,X_______,________,
  __XXXXXX,XX______,________,
  _XXXXXXX,XXXX____,__XXX___,
  XXXXX__X,XXXXX___,_XXXX___,
  XXXX____,XXXXXXX_,_XXXX___,
  XXXX____,__XXXXXX,_XXXX___,
  XXXX____,___XXXXX,XXXXX___,
  XXXXX___,_____XXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0027[  9] = { /* code 0027, APOSTROPHE */
  _XX_____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0028[ 25] = { /* code 0028, LEFT PARENTHESIS */
  ____XX__,
  ___XXXX_,
  __XXXXX_,
  _XXXXXX_,
  XXXXXX__,
  XXXXX___,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXXX___,
  XXXXXX__,
  _XXXXXX_,
  __XXXXX_,
  ___XXXX_,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0029[ 25] = { /* code 0029, RIGHT PARENTHESIS */
  _XX_____,
  XXXX____,
  XXXXX___,
  XXXXXX__,
  _XXXXXX_,
  __XXXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  __XXXXX_,
  _XXXXXX_,
  XXXXXX__,
  XXXXX___,
  XXXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_002A[ 75] = { /* code 002A, ASTERISK */
  ________,___XX___,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  _XXX____,__XXXX__,________,
  _XXXX___,__XXXX__,_____XX_,
  _XXXXXX_,__XXXX__,___XXXXX,
  _XXXXXXX,__XXXX__,_XXXXXXX,
  ___XXXXX,XXXXXX_X,XXXXXXX_,
  ____XXXX,XXXXXXXX,XXXXX___,
  ______XX,XXXXXXXX,XXX_____,
  _______X,XXXXXXXX,XX______,
  ________,XXXXXXXX,________,
  ______XX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,X_XXXXXX,XXXXX___,
  XXXXXXX_,__XXXX__,XXXXXXX_,
  XXXXX___,__XXXX__,_XXXXXX_,
  _XX_____,__XXXX__,___XXXX_,
  ________,__XXXX__,____XXX_,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_002B[ 75] = { /* code 002B, PLUS SIGN */
  ________,___XX___,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_002C[  8] = { /* code 002C, COMMA */
  ____XXX_,
  ___XXXXX,
  __XXXXXX,
  _XXXXXX_,
  XXXXXX__,
  XXXXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_002D[  8] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_002E[  6] = { /* code 002E, FULL STOP */
  _XXXX___,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_002F[ 63] = { /* code 002F, SOLIDUS */
  ________,________,__XXX___,
  ________,________,_XXXX___,
  ________,________,XXXXX___,
  ________,_______X,XXXX____,
  ________,______XX,XXX_____,
  ________,_____XXX,XX______,
  ________,____XXXX,X_______,
  ________,___XXXXX,________,
  ________,__XXXXX_,________,
  ________,_XXXXX__,________,
  ________,XXXXX___,________,
  _______X,XXXX____,________,
  ______XX,XXX_____,________,
  _____XXX,XX______,________,
  ____XXXX,X_______,________,
  ___XXXXX,________,________,
  __XXXXX_,________,________,
  _XXXXX__,________,________,
  XXXXX___,________,________,
  XXXX____,________,________,
  XXX_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0030[ 72] = { /* code 0030, DIGIT ZERO */
  _____XXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX___,________,___XXXX_,
  XXXX____,________,____XXXX,
  XXXX____,________,___XXXXX,
  XXXX____,________,_XXXXXXX,
  XXXX____,_______X,XXXXXXXX,
  XXXX____,_____XXX,XXXXXXXX,
  XXXX____,___XXXXX,XXXXXXXX,
  XXXX____,_XXXXXXX,XX__XXXX,
  XXXX__XX,XXXXXXXX,____XXXX,
  XXXXXXXX,XXXXXX__,____XXXX,
  XXXXXXXX,XXXX____,____XXXX,
  XXXXXXXX,XX______,____XXXX,
  XXXXXXXX,________,____XXXX,
  XXXXXX__,________,____XXXX,
  XXXX____,________,____XXXX,
  _XXXX___,________,___XXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXX___,
  _____XXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0031[ 72] = { /* code 0031, DIGIT ONE */
  _______X,X_______,________,
  ______XX,XX______,________,
  _____XXX,XX______,________,
  ____XXXX,XX______,________,
  ___XXXXX,XX______,________,
  __XXXXXX,XX______,________,
  _XXXXXXX,XX______,________,
  _XXXXXXX,XX______,________,
  __XXX_XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  ______XX,XX______,________,
  XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0032[ 75] = { /* code 0032, DIGIT TWO */
  _XXXXXXX,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,___XXXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,___XXXXX,
  _____XXX,XXXXXXXX,XXXXXXX_,
  ___XXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXX____,
  XXXXXX__,________,________,
  XXXXX___,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  _____XXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0033[ 72] = { /* code 0033, DIGIT THREE */
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,___XXXX_,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ____XXXX,XXXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  ____XXXX,XXXXXXXX,XXXXXXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,___XXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0034[ 75] = { /* code 0034, DIGIT FOUR */
  _XX_____,_______X,X_______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  XXXX____,______XX,XX______,
  _XXXX___,______XX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  _____XXX,XXXXXXXX,XXXXXXX_,
  ________,______XX,XX______,
  ________,______XX,XX______,
  ________,______XX,XX______,
  ________,______XX,XX______,
  ________,______XX,XX______,
  ________,______XX,XX______,
  ________,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0035[ 72] = { /* code 0035, DIGIT FIVE */
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,___XXXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,___XXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0036[100] = { /* code 0036, DIGIT SIX */
  _____XXX,XXXXX___,________,________,
  ___XXXXX,XXXXXXXX,XXXX____,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXX___,________,___XXXXX,X_______,
  XXXX____,________,____XXXX,X_______,
  XXXX____,________,_____XXX,X_______,
  XXXX____,________,______XX,________,
  XXXX____,________,________,________,
  XXXX____,________,________,________,
  XXXXXXXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXX____,________,___XXXXX,________,
  XXXX____,________,____XXXX,X_______,
  XXXX____,________,_____XXX,X_______,
  XXXX____,________,_____XXX,X_______,
  XXXX____,________,_____XXX,X_______,
  _XXXXX__,________,____XXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  _____XXX,XXXXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0037[ 78] = { /* code 0037, DIGIT SEVEN */
  _XXXXXXX,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,___XXXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,___XXXXX,
  ________,_______X,XXXXXXXX,
  ________,_____XXX,XXXXXXX_,
  ________,____XXXX,XXXXXX__,
  ________,___XXXXX,XXXX____,
  ________,__XXXXXX,________,
  ________,__XXXXX_,________,
  ________,__XXXX__,________,
  ________,_XXXXX__,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,XXXXX___,________,
  ________,XXXXX___,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0038[ 72] = { /* code 0038, DIGIT EIGHT */
  _____XXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX___,________,__XXXXX_,
  XXXX____,________,___XXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  _XXXX___,________,___XXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX___,________,___XXXX_,
  XXXX____,________,___XXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  _XXXX___,________,___XXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXX___,
  _____XXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0039[ 72] = { /* code 0039, DIGIT NINE */
  ____XXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXX___,________,__XXXXX_,
  XXXX____,________,___XXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXXX___,________,____XXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  ____XXXX,XXXXXXXX,XXXXXXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  ________,________,____XXXX,
  XXX_____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXXX___,________,___XXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_003A[ 16] = { /* code 003A, COLON */
  _XXX____,
  XXXXX___,
  XXXXXX__,
  XXXXXX__,
  XXXXX___,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  XXXXX___,
  XXXXXX__,
  XXXXXX__,
  XXXXX___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_003B[ 18] = { /* code 003B, SEMICOLON */
  ___XXXX_,
  __XXXXXX,
  __XXXXXX,
  __XXXXXX,
  __XXXXXX,
  ___XXXX_,
  ________,
  ________,
  ________,
  ________,
  ____XXXX,
  ___XXXXX,
  __XXXXXX,
  _XXXXXX_,
  XXXXXX__,
  XXXXX___,
  XXXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_003C[ 34] = { /* code 003C, LESS-THAN SIGN */
  _______X,XX______,
  ______XX,XXX_____,
  _____XXX,XXX_____,
  ____XXXX,XXX_____,
  ___XXXXX,XX______,
  __XXXXXX,X_______,
  _XXXXXXX,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  _XXXXXXX,________,
  __XXXXXX,X_______,
  ___XXXXX,XX______,
  ____XXXX,XXX_____,
  _____XXX,XXX_____,
  ______XX,XXX_____,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_003D[ 24] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_003E[ 34] = { /* code 003E, GREATER-THAN SIGN */
  _XXX____,________,
  XXXXX___,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  _XXXXXXX,________,
  __XXXXXX,X_______,
  ___XXXXX,XX______,
  ____XXXX,XXX_____,
  _____XXX,XXX_____,
  ____XXXX,XXX_____,
  ___XXXXX,XX______,
  __XXXXXX,X_______,
  _XXXXXXX,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XXXXX___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_003F[ 72] = { /* code 003F, QUESTION MARK */
  ____XXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXX___,________,___XXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,___XXXXX,
  ________,__XXXXXX,XXXXXXX_,
  ________,__XXXXXX,XXXXXX__,
  ________,__XXXXXX,XXXXX___,
  ________,__XXXXXX,XXXX____,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,________,________,
  ________,________,________,
  ________,__XXXX__,________,
  ________,_XXXXXX_,________,
  ________,_XXXXXX_,________,
  ________,_XXXXXX_,________,
  ________,_XXXXXX_,________,
  ________,__XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0040[ 75] = { /* code 0040, COMMERCIAL AT */
  ____XXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXX___,________,___XXXXX,
  XXXX____,___XXXXX,X___XXXX,
  XXXX____,_XXXXXXX,X___XXXX,
  XXXX____,XXXXXXXX,X___XXXX,
  XXXX___X,XXXXXXXX,X___XXXX,
  XXXX__XX,XXXXXXXX,X___XXXX,
  XXXX__XX,XXX__XXX,X___XXXX,
  XXXX__XX,XX___XXX,X___XXXX,
  XXXX__XX,XX___XXX,X___XXXX,
  XXXX__XX,XXX__XXX,X__XXXXX,
  XXXX__XX,XXXX_XXX,X_XXXXXX,
  XXXX___X,XXXXXXXX,XXXXXXX_,
  XXXX____,XXXXXXXX,XXXXXX__,
  XXXX____,_XXXXXXX,XXXXXXXX,
  XXXXX___,___XXXXX,XXXXXXXX,
  XXXXXX__,________,__XXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0041[ 72] = { /* code 0041, LATIN CAPITAL LETTER A */
  _______X,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XXX,X______X,XXXX____,
  ____XXXX,X_______,XXXX____,
  ____XXXX,________,XXXX____,
  ____XXXX,________,XXXXX___,
  ___XXXXX,________,XXXXX___,
  ___XXXX_,________,_XXXX___,
  ___XXXX_,________,_XXXX___,
  ___XXXX_,________,_XXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX___,________,___XXXX_,
  _XXXX___,________,___XXXX_,
  XXXXX___,________,___XXXX_,
  XXXXX___,________,___XXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  ________,________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0042[ 72] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXX____,________,___XXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,___XXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXX____,________,___XXXXX,
  XXXX____,________,___XXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,___XXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0043[100] = { /* code 0043, LATIN CAPITAL LETTER C */
  _____XXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXX__,________,___XXXXX,X_______,
  _XXXX___,________,____XXXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,________,________,
  _XXXX___,________,_____XXX,X_______,
  _XXXXX__,________,____XXXX,X_______,
  _XXXXXX_,________,___XXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXX__,________,
  _____XXX,XXXXXXXX,XXXXX___,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0044[ 72] = { /* code 0044, LATIN CAPITAL LETTER D */
  _XXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ___XXXX_,________,___XXXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,____XXXX,
  ___XXXX_,________,___XXXXX,
  ___XXXX_,________,__XXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0045[ 72] = { /* code 0045, LATIN CAPITAL LETTER E */
  ____XXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXX__,________,________,
  XXXXX___,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXXX___,________,________,
  XXXXXX__,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  ____XXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0046[ 72] = { /* code 0046, LATIN CAPITAL LETTER F */
  _____XXX,XXXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXX__,________,________,
  XXXXX___,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0047[ 96] = { /* code 0047, LATIN CAPITAL LETTER G */
  ______XX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXX_,________,____XXXX,X_______,
  _XXXXX__,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,______XX,________,
  _XXXX___,________,________,________,
  _XXXX___,__XXXXXX,XXXXXXXX,X_______,
  _XXXX___,__XXXXXX,XXXXXXXX,X_______,
  _XXXX___,__XXXXXX,XXXXXXXX,X_______,
  _XXXX___,__XXXXXX,XXXXXXXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXXX__,________,_____XXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0048[ 75] = { /* code 0048, LATIN CAPITAL LETTER H */
  _XX_____,________,________,
  XXXX____,________,_____XX_,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  _XXX____,________,____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0049[ 25] = { /* code 0049, LATIN CAPITAL LETTER I */
  __X_____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_004A[ 96] = { /* code 004A, LATIN CAPITAL LETTER J */
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  ________,________,_XXXX___,________,
  XXXX____,________,_XXXX___,________,
  XXXX____,________,_XXXX___,________,
  XXXX____,________,_XXXX___,________,
  XXXX____,________,_XXXX___,________,
  XXXXX___,________,_XXXX___,________,
  XXXXXX__,_______X,XXXXX___,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,________,
  _XXXXXXX,XXXXXXXX,XXXX____,________,
  __XXXXXX,XXXXXXXX,XXX_____,________,
  ____XXXX,XXXXXXXX,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_004B[ 72] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXX_____,________,__XXXXXX,
  XXXX____,________,XXXXXXXX,
  XXXX____,______XX,XXXXXXXX,
  XXXX____,____XXXX,XXXXXXXX,
  XXXX____,___XXXXX,XXX_____,
  XXXX____,_XXXXXXX,X_______,
  XXXX___X,XXXXXXX_,________,
  XXXX__XX,XXXXXX__,________,
  XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXX___,________,
  XXXXXXX_,XXXXXX__,________,
  XXXXX___,_XXXXX__,________,
  XXXX____,__XXXXX_,________,
  XXXX____,___XXXXX,________,
  XXXX____,___XXXXX,X_______,
  XXXX____,____XXXX,X_______,
  XXXX____,_____XXX,XX______,
  XXXX____,______XX,XXX_____,
  XXXX____,______XX,XXXX____,
  XXXX____,_______X,XXXXXXX_,
  XXXX____,________,XXXXXXXX,
  XXXX____,________,_XXXXXXX,
  XXXX____,________,_XXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_004C[ 72] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  ____XXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_004D[ 96] = { /* code 004D, LATIN CAPITAL LETTER M */
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXX__,_____XXX,X_______,XXXXXX__,
  XXXXX___,_____XXX,X_______,_XXXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,______XX,X_______,__XXXX__,
  XXXX____,________,________,__XXXX__,
  XXXX____,________,________,__XXXX__,
  XXXX____,________,________,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_004E[ 72] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXX____,________,___XXXXX,
  XXXX____,________,___XXXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_004F[ 96] = { /* code 004F, LATIN CAPITAL LETTER O */
  ______XX,XXXXXXXX,XXXXXX__,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXX_,________,_____XXX,XX______,
  _XXXXX__,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  _XXXX___,________,______XX,XX______,
  __XXXX__,________,____XXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXX_,________,
  ______XX,XXXXXXXX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0050[104] = { /* code 0050, LATIN CAPITAL LETTER P */
  __XXXXXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXX____,________,__XXXXXX,________,
  XXXX____,________,___XXXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,___XXXXX,________,
  XXXX____,________,___XXXXX,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXXXX,XXXX____,________,
  XXXX____,________,________,________,
  XXXX____,________,________,________,
  XXXX____,________,________,________,
  XXXX____,________,________,________,
  XXXX____,________,________,________,
  XXXX____,________,________,________,
  XXXX____,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0051[100] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _____XXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXX__,________,____XXXX,________,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXX___,___XXXX_,_____XXX,X_______,
  _XXXX___,__XXXXXX,_____XXX,X_______,
  _XXXX___,__XXXXXX,X____XXX,X_______,
  _XXXX___,___XXXXX,XX___XXX,X_______,
  _XXXX___,____XXXX,XXX__XXX,X_______,
  _XXXX___,_____XXX,XXXX_XXX,X_______,
  _XXXX___,______XX,XXXXXXXX,X_______,
  _XXXX___,_______X,XXXXXXXX,X_______,
  _XXXXX__,________,XXXXXXXX,X_______,
  _XXXXXX_,________,_XXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0052[ 96] = { /* code 0052, LATIN CAPITAL LETTER R */
  __XXXXXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXX____,________,__XXXXXX,________,
  XXXX____,________,___XXXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,____XXXX,________,
  XXXX____,________,___XXXXX,________,
  XXXX____,________,__XXXXXX,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXXXX,XXX_____,________,
  XXXX____,______XX,XXXX____,________,
  XXXX____,_______X,XXXXX___,________,
  XXXX____,________,XXXXXX__,________,
  XXXX____,________,_XXXXXX_,________,
  XXXX____,________,__XXXXXX,________,
  XXXX____,________,___XXXXX,________,
  XXXX____,________,____XXXX,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0053[ 96] = { /* code 0053, LATIN CAPITAL LETTER S */
  ______XX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXX_,________,____XXXX,X_______,
  _XXXXX__,________,_____XXX,XX______,
  _XXXX___,________,______XX,X_______,
  _XXXX___,________,________,________,
  _XXXXX__,________,________,________,
  _XXXXXX_,________,________,________,
  __XXXXXX,XXXXXXXX,XXXXX___,________,
  ___XXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,XXXXXXXX,________,
  ________,________,___XXXXX,X_______,
  ________,________,____XXXX,X_______,
  ________,________,_____XXX,X_______,
  _XXX____,________,_____XXX,X_______,
  _XXXX___,________,_____XXX,X_______,
  _XXXXXX_,________,____XXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0054[ 72] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0055[ 75] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXXX___,________,___XXXXX,
  XXXXXX__,________,__XXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXX_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0056[ 75] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,________,________,
  XXX_____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXXX___,________,___XXXXX,
  _XXXX___,________,___XXXXX,
  _XXXX___,________,___XXXX_,
  _XXXXX__,________,__XXXXX_,
  _XXXXX__,________,__XXXXX_,
  __XXXX__,________,__XXXX__,
  __XXXX__,________,_XXXXX__,
  __XXXXX_,________,_XXXXX__,
  ___XXXX_,________,_XXXX___,
  ___XXXX_,________,XXXXX___,
  ___XXXXX,________,XXXXX___,
  ____XXXX,________,XXXX____,
  ____XXXX,________,XXXX____,
  ____XXXX,X______X,XXXX____,
  ____XXXX,X______X,XXX_____,
  _____XXX,X______X,XXX_____,
  _____XXX,XX____XX,XXX_____,
  _____XXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,XX______,
  ________,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0057[ 96] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX____,________,________,__XXXX__,
  XXXX____,________,________,__XXXX__,
  XXXX____,________,________,__XXXX__,
  XXXX____,_____XXX,________,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXX____,_____XXX,X_______,__XXXX__,
  XXXXX___,_____XXX,X_______,_XXXXX__,
  XXXXXX__,_____XXX,X_______,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0058[ 96] = { /* code 0058, LATIN CAPITAL LETTER X */
  _XXXXXX_,________,__XXXXXX,X_______,
  XXXXXXXX,________,_XXXXXXX,X_______,
  XXXXXXXX,________,XXXXXXXX,X_______,
  _XXXXXXX,X_______,XXXXXXXX,________,
  _____XXX,XX_____X,XXXX____,________,
  _____XXX,XXX___XX,XXX_____,________,
  ______XX,XXX___XX,XXX_____,________,
  _______X,XXXX_XXX,XX______,________,
  _______X,XXXXXXXX,X_______,________,
  ________,XXXXXXXX,X_______,________,
  ________,_XXXXXXX,________,________,
  ________,_XXXXXX_,________,________,
  ________,_XXXXXX_,________,________,
  ________,_XXXXXXX,________,________,
  ________,XXXXXXXX,X_______,________,
  _______X,XXXXXXXX,X_______,________,
  _______X,XXXX_XXX,XX______,________,
  ______XX,XXX___XX,XXX_____,________,
  _____XXX,XX____XX,XXX_____,________,
  _____XXX,XX_____X,XXXX____,________,
  _XXXXXXX,X_______,XXXXXXXX,________,
  XXXXXXXX,________,_XXXXXXX,X_______,
  XXXXXXX_,________,_XXXXXXX,X_______,
  XXXXXX__,________,__XXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0059[ 75] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,________,________,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXX____,________,____XXXX,
  XXXXX___,________,___XXXXX,
  XXXXXX__,________,__XXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXX_____,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_005A[ 96] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,________,___XXXXX,________,
  ________,________,__XXXXXX,________,
  ________,________,_XXXXXX_,________,
  ________,_______X,XXXXXXX_,________,
  ________,______XX,XXXXX___,________,
  ________,____XXXX,XXXX____,________,
  ________,___XXXXX,XX______,________,
  ________,_XXXXXXX,X_______,________,
  ________,XXXXXXXX,________,________,
  _______X,XXXXXX__,________,________,
  _____XXX,XXXXX___,________,________,
  ____XXXX,XXX_____,________,________,
  __XXXXXX,XX______,________,________,
  _XXXXXXX,________,________,________,
  XXXXXXX_,________,________,________,
  XXXXXX__,________,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_005B[ 48] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_005C[ 63] = { /* code 005C, REVERSE SOLIDUS */
  XXX_____,________,________,
  XXXX____,________,________,
  XXXXX___,________,________,
  _XXXXX__,________,________,
  __XXXXX_,________,________,
  ___XXXXX,________,________,
  ____XXXX,X_______,________,
  _____XXX,XX______,________,
  ______XX,XXX_____,________,
  _______X,XXXX____,________,
  ________,XXXXX___,________,
  ________,_XXXXX__,________,
  ________,__XXXXX_,________,
  ________,___XXXXX,________,
  ________,____XXXX,X_______,
  ________,_____XXX,XX______,
  ________,______XX,XXX_____,
  ________,_______X,XXXX____,
  ________,________,XXXXX___,
  ________,________,_XXXX___,
  ________,________,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_005D[ 48] = { /* code 005D, RIGHT SQUARE BRACKET */
  _XXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _XXXXXXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _XXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_005E[ 36] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,XX______,________,
  _______X,XXX_____,________,
  ______XX,XXXX____,________,
  _____XXX,XXXXX___,________,
  ____XXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXX_,________,
  __XXXXXX,__XXXXXX,________,
  _XXXXXX_,___XXXXX,X_______,
  XXXXXX__,____XXXX,XX______,
  XXXXX___,_____XXX,XX______,
  XXXX____,______XX,XX______,
  _XX_____,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_005F[ 12] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0060[  8] = { /* code 0060, GRAVE ACCENT */
  _XX_____,
  XXXX____,
  XXXXX___,
  XXXXXX__,
  _XXXXXX_,
  __XXXXXX,
  ____XXXX,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0061[ 48] = { /* code 0061, LATIN SMALL LETTER A */
  ____XXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _XXXX___,________,XXXXX___,
  __X_____,________,_XXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXX_____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0062[ 63] = { /* code 0062, LATIN SMALL LETTER B */
  _XX_____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXX____,_______X,XXXXX___,
  XXXX____,________,XXXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  XXXXXX__,_______X,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0063[ 48] = { /* code 0063, LATIN SMALL LETTER C */
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  XXXXXX__,________,XXXXX___,
  XXXXX___,________,_XXXXX__,
  XXXX____,________,__XXX___,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,__XXX___,
  XXXXX___,________,_XXXXX__,
  XXXXXX__,________,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0064[ 63] = { /* code 0064, LATIN SMALL LETTER D */
  ________,________,__XX____,
  ________,________,_XXXX___,
  ________,________,_XXXX___,
  ________,________,_XXXX___,
  ________,________,_XXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXX__,________,_XXXX___,
  XXXXX___,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  XXXXXX__,_______X,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0065[ 48] = { /* code 0065, LATIN SMALL LETTER E */
  ____XXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXX___,________,XXXXX___,
  XXX_____,________,_XXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXX_____,________,_XX_____,
  XXXXX___,________,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0066[ 63] = { /* code 0066, LATIN SMALL LETTER F */
  ________,_XXXXXXX,X_______,
  ________,XXXXXXXX,X_______,
  ______XX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____XXX,XX______,________,
  _____XXX,X_______,________,
  _XXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXX___,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  ______XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0067[ 66] = { /* code 0067, LATIN SMALL LETTER G */
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  XXXXX___,________,XXXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ________,________,XXXXX___,
  ________,________,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0068[ 63] = { /* code 0068, LATIN SMALL LETTER H */
  _XX_____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXX__,_______X,XXXXX___,
  XXXXX___,________,XXXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  _XX_____,________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0069[ 22] = { /* code 0069, LATIN SMALL LETTER I */
  _XX_____,
  XXXX____,
  XXXX____,
  _XX_____,
  ________,
  ________,
  _XX_____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_006A[ 52] = { /* code 006A, LATIN SMALL LETTER J */
  _______X,X_______,
  ______XX,XX______,
  ______XX,XX______,
  _______X,X_______,
  ________,________,
  ________,________,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  _____XXX,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_006B[ 63] = { /* code 006B, LATIN SMALL LETTER K */
  _XX_____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,_______X,XXXXX___,
  XXXX____,____XXXX,XXXXXX__,
  XXXX____,__XXXXXX,XXXXXX__,
  XXXX___X,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXXX____,________,
  XXXXX___,XXXXX___,________,
  XXXX____,_XXXXX__,________,
  XXXX____,__XXXXX_,________,
  XXXX____,___XXXXX,X_______,
  XXXX____,____XXXX,XXXXX___,
  XXXX____,_____XXX,XXXXXX__,
  XXXX____,______XX,XXXXXX__,
  _XX_____,_______X,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_006C[ 21] = { /* code 006C, LATIN SMALL LETTER L */
  XXX_____,
  XXXX____,
  XXXXX___,
  _XXXXX__,
  __XXXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_006D[ 64] = { /* code 006D, LATIN SMALL LETTER M */
  _XX_____,________,________,________,
  XXXXXXXX,XXXXX_XX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  _XX_____,_____XX_,________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_006E[ 48] = { /* code 006E, LATIN SMALL LETTER N */
  _XX_____,________,________,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  _XX_____,________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_006F[ 48] = { /* code 006F, LATIN SMALL LETTER O */
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  XXXXX___,________,XXXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0070[ 63] = { /* code 0070, LATIN SMALL LETTER P */
  ____XXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXX___,________,XXXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,X_______,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  _XX_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0071[ 63] = { /* code 0071, LATIN SMALL LETTER Q */
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  XXXXX___,________,XXXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ________,________,_XXXX___,
  ________,________,_XXXX___,
  ________,________,_XXXX___,
  ________,________,_XXXX___,
  ________,________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0072[ 48] = { /* code 0072, LATIN SMALL LETTER R */
  _XXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXX____,________,__XXXX__,
  XXXX____,________,__XXX___,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  XXXX____,________,________,
  _XX_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0073[ 48] = { /* code 0073, LATIN SMALL LETTER S */
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXX___,________,XXXXX___,
  XXXX____,________,_XXXX___,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  XXXX____,________,__XXX___,
  XXXXX___,________,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0074[ 63] = { /* code 0074, LATIN SMALL LETTER T */
  ______XX,________,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _XXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXX___,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,XX______,________,
  _____XXX,XXXXXXXX,X_______,
  ______XX,XXXXXXXX,X_______,
  ________,XXXXXXXX,X_______,
  ________,_XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0075[ 48] = { /* code 0075, LATIN SMALL LETTER U */
  _XX_____,________,__XX____,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  XXXXXX__,_______X,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0076[ 48] = { /* code 0076, LATIN SMALL LETTER V */
  _XX_____,________,__XX____,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  _XXXXX__,_______X,XXXX____,
  __XXXXX_,______XX,XXX_____,
  ___XXXXX,_____XXX,XX______,
  ____XXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,________,
  _______X,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0077[ 64] = { /* code 0077, LATIN SMALL LETTER W */
  _XX_____,_____XX_,________,_XX_____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXX____,____XXXX,________,XXXX____,
  XXXXX___,____XXXX,_______X,XXXX____,
  XXXXXX__,____XXXX,______XX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0078[ 48] = { /* code 0078, LATIN SMALL LETTER X */
  XXXXX___,_______X,XXXXX___,
  XXXXXXX_,______XX,XXXXX___,
  XXXXXXXX,_____XXX,XXXXX___,
  XXXXXXXX,X___XXXX,XXXXX___,
  ____XXXX,XX_XXXXX,X_______,
  _____XXX,XXXXXXXX,________,
  ______XX,XXXXXXX_,________,
  _______X,XXXXXX__,________,
  _______X,XXXXXX__,________,
  ______XX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,________,
  ____XXXX,XX_XXXXX,X_______,
  XXXXXXXX,X___XXXX,XXXX____,
  XXXXXXXX,_____XXX,XXXXX___,
  XXXXXXX_,______XX,XXXXX___,
  XXXXX___,_______X,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_0079[ 63] = { /* code 0079, LATIN SMALL LETTER Y */
  _XX_____,________,__XX____,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXX____,________,_XXXX___,
  XXXXX___,________,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,X_______,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,_XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_007A[ 48] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,________,XXXXX___,
  ________,_____XXX,XXXXX___,
  ________,__XXXXXX,XXXX____,
  _______X,XXXXXXXX,XX______,
  ___XXXXX,XXXXXX__,________,
  _XXXXXXX,XXX_____,________,
  XXXXXXXX,________,________,
  XXXXX___,________,________,
  _XXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_007E[ 21] = { /* code 007E, TILDE */
  ___XXXXX,XXX_____,__XXX___,
  __XXXXXX,XXXX____,_XXXXX__,
  _XXXXXXX,XXXXX___,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXX___,_XXXXXXX,XXXX____,
  XXXX____,__XXXXXX,XXX_____,
  _XX_____,___XXXXX,XX______};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_00A0[  1] = { /* code 00A0, NO-BREAK SPACE */
  ________};

/* Start of unicode area <Special> */
GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics40_FFFF[ 78] = { /* code FFFF */
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______,
  XXX_____,_______X,XX______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDigitGraphics40_CharInfo[94] = {
   {   1,   1,   0,  26,   4, acGUI_FontDigitGraphics40_0020 } /* code 0020, SPACE */
  ,{   4,  24,   3,   2,   8, acGUI_FontDigitGraphics40_0021 } /* code 0021, EXCLAMATION MARK */
  ,{  12,   9,   3,   3,  16, acGUI_FontDigitGraphics40_0022 } /* code 0022, QUOTATION MARK */
  ,{  25,  25,   3,   1,  29, acGUI_FontDigitGraphics40_0023 } /* code 0023, NUMBER SIGN */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0024 } /* code 0024, DOLLAR SIGN */
  ,{  24,  25,   3,   1,  29, acGUI_FontDigitGraphics40_0025 } /* code 0025, PERCENT SIGN */
  ,{  21,  22,   3,   4,  26, acGUI_FontDigitGraphics40_0026 } /* code 0026, AMPERSAND */
  ,{   4,   9,   3,   3,   8, acGUI_FontDigitGraphics40_0027 } /* code 0027, APOSTROPHE */
  ,{   7,  25,   3,   1,  12, acGUI_FontDigitGraphics40_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   7,  25,   3,   1,  12, acGUI_FontDigitGraphics40_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{  24,  25,   3,   1,  28, acGUI_FontDigitGraphics40_002A } /* code 002A, ASTERISK */
  ,{  24,  25,   3,   1,  29, acGUI_FontDigitGraphics40_002B } /* code 002B, PLUS SIGN */
  ,{   8,   8,   3,  19,  12, acGUI_FontDigitGraphics40_002C } /* code 002C, COMMA */
  ,{  15,   4,   3,  14,  19, acGUI_FontDigitGraphics40_002D } /* code 002D, HYPHEN-MINUS */
  ,{   6,   6,   3,  19,  10, acGUI_FontDigitGraphics40_002E } /* code 002E, FULL STOP */
  ,{  21,  21,   3,   4,  26, acGUI_FontDigitGraphics40_002F } /* code 002F, SOLIDUS */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0030 } /* code 0030, DIGIT ZERO */
  ,{  17,  24,   3,   2,  22, acGUI_FontDigitGraphics40_0031 } /* code 0031, DIGIT ONE */
  ,{  24,  25,   3,   1,  29, acGUI_FontDigitGraphics40_0032 } /* code 0032, DIGIT TWO */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0033 } /* code 0033, DIGIT THREE */
  ,{  24,  25,   3,   1,  29, acGUI_FontDigitGraphics40_0034 } /* code 0034, DIGIT FOUR */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0035 } /* code 0035, DIGIT FIVE */
  ,{  25,  25,   3,   1,  29, acGUI_FontDigitGraphics40_0036 } /* code 0036, DIGIT SIX */
  ,{  24,  26,   3,   1,  29, acGUI_FontDigitGraphics40_0037 } /* code 0037, DIGIT SEVEN */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0038 } /* code 0038, DIGIT EIGHT */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0039 } /* code 0039, DIGIT NINE */
  ,{   6,  16,   3,   6,  10, acGUI_FontDigitGraphics40_003A } /* code 003A, COLON */
  ,{   8,  18,   3,   7,  12, acGUI_FontDigitGraphics40_003B } /* code 003B, SEMICOLON */
  ,{  11,  17,   3,   6,  16, acGUI_FontDigitGraphics40_003C } /* code 003C, LESS-THAN SIGN */
  ,{  13,  12,   3,   9,  17, acGUI_FontDigitGraphics40_003D } /* code 003D, EQUALS SIGN */
  ,{  11,  17,   3,   6,  16, acGUI_FontDigitGraphics40_003E } /* code 003E, GREATER-THAN SIGN */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_003F } /* code 003F, QUESTION MARK */
  ,{  24,  25,   3,   1,  29, acGUI_FontDigitGraphics40_0040 } /* code 0040, COMMERCIAL AT */
  ,{  24,  24,   3,   2,  28, acGUI_FontDigitGraphics40_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  25,  25,   2,   2,  29, acGUI_FontDigitGraphics40_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  25,  24,   2,   2,  29, acGUI_FontDigitGraphics40_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  24,  25,   3,   1,  29, acGUI_FontDigitGraphics40_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   4,  25,   3,   1,   8, acGUI_FontDigitGraphics40_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  25,  24,   3,   2,  30, acGUI_FontDigitGraphics40_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  24,  24,   3,   2,  28, acGUI_FontDigitGraphics40_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  30,  24,   3,   2,  34, acGUI_FontDigitGraphics40_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  24,  24,   3,   2,  28, acGUI_FontDigitGraphics40_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  26,  24,   2,   2,  29, acGUI_FontDigitGraphics40_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  25,  26,   3,   2,  29, acGUI_FontDigitGraphics40_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  26,  25,   3,   2,  30, acGUI_FontDigitGraphics40_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  25,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  26,  24,   3,   2,  30, acGUI_FontDigitGraphics40_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  24,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  24,  25,   3,   2,  28, acGUI_FontDigitGraphics40_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  24,  25,   3,   1,  29, acGUI_FontDigitGraphics40_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  30,  24,   3,   2,  34, acGUI_FontDigitGraphics40_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  25,  24,   3,   2,  29, acGUI_FontDigitGraphics40_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  24,  25,   3,   1,  28, acGUI_FontDigitGraphics40_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  25,  24,   3,   2,  30, acGUI_FontDigitGraphics40_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   9,  24,   3,   2,  13, acGUI_FontDigitGraphics40_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{  21,  21,   3,   5,  26, acGUI_FontDigitGraphics40_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   9,  24,   3,   2,  13, acGUI_FontDigitGraphics40_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{  18,  12,   3,   3,  22, acGUI_FontDigitGraphics40_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{  24,   4,   3,  22,  29, acGUI_FontDigitGraphics40_005F } /* code 005F, LOW LINE */
  ,{   8,   8,   3,   8,  12, acGUI_FontDigitGraphics40_0060 } /* code 0060, GRAVE ACCENT */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  21,  21,   3,   5,  26, acGUI_FontDigitGraphics40_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{  22,  16,   3,  10,  26, acGUI_FontDigitGraphics40_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  21,  21,   3,   5,  26, acGUI_FontDigitGraphics40_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{  17,  21,   2,   5,  21, acGUI_FontDigitGraphics40_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  21,  22,   3,  10,  26, acGUI_FontDigitGraphics40_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  21,  21,   3,   5,  26, acGUI_FontDigitGraphics40_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   4,  22,   3,   4,   9, acGUI_FontDigitGraphics40_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{  10,  26,   2,   5,  14, acGUI_FontDigitGraphics40_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  22,  21,   3,   5,  26, acGUI_FontDigitGraphics40_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   7,  21,   3,   5,  11, acGUI_FontDigitGraphics40_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  28,  16,   3,  10,  32, acGUI_FontDigitGraphics40_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  21,  21,   3,  10,  26, acGUI_FontDigitGraphics40_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  21,  21,   3,  10,  26, acGUI_FontDigitGraphics40_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{  22,  16,   3,  10,  26, acGUI_FontDigitGraphics40_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{  17,  21,   2,   5,  21, acGUI_FontDigitGraphics40_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  28,  16,   3,  10,  31, acGUI_FontDigitGraphics40_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  21,  21,   3,  10,  26, acGUI_FontDigitGraphics40_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{  21,  16,   3,  10,  26, acGUI_FontDigitGraphics40_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{  22,   7,   3,   6,  26, acGUI_FontDigitGraphics40_007E } /* code 007E, TILDE */
  ,{   1,   1,   0,  26,   4, acGUI_FontDigitGraphics40_00A0 } /* code 00A0, NO-BREAK SPACE */
  ,{  18,  26,   3,   0,  22, acGUI_FontDigitGraphics40_FFFF } /* code FFFF */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDigitGraphics40_Prop4 = {
   0xFFFF /* first character */
  ,0xFFFF /* last character  */
  ,&GUI_FontDigitGraphics40_CharInfo[ 93] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDigitGraphics40_Prop3 = {
   0x00A0 /* first character */
  ,0x00A0 /* last character  */
  ,&GUI_FontDigitGraphics40_CharInfo[ 92] /* address of first character */
  ,&GUI_FontDigitGraphics40_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDigitGraphics40_Prop2 = {
   0x007E /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontDigitGraphics40_CharInfo[ 91] /* address of first character */
  ,&GUI_FontDigitGraphics40_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDigitGraphics40_Prop1 = {
   0x0020 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontDigitGraphics40_CharInfo[  0] /* address of first character */
  ,&GUI_FontDigitGraphics40_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDigitGraphics40 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,32 /* height of font  */
  ,32 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDigitGraphics40_Prop1}
  ,26 /* Baseline */
  ,16 /* Height of lowercase characters */
  ,24 /* Height of capital characters */
};

