/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_outdoor                                          *
* Dimensions:  40 * 37                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_outdoor;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsicon_outdoor[] = {
#if (GUI_USE_ARGB == 0)
  0xCECECE, 0x000000
#else
  0xFFCECECE,0xFF000000
#endif
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palicon_outdoor = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsicon_outdoor[0]
};

static GUI_CONST_STORAGE unsigned char _acicon_outdoor[] = {
  XXXXXXXX, XXXXX_XX, XXXXXXXX, XX_XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX__X, XXXXXXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, XXXXXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _XXXXXX_, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, __XXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _XXXXXX_, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX__X, XXXXXXXX, X___XXXX, XXXXXXXX,
  XXX____X, XXXXXXXX, XX____XX, XXXXXXXX, X____XXX,
  XXXX____, __XXXXX_, ________, _XXXXX__, ____XXXX,
  XXXX____, _XXXX___, ________, ___XXXX_, ____XXXX,
  XXXXX___, _XXX____, ________, ____XXX_, ___XXXXX,
  XXXXX___, XXX_____, ________, _____XXX, ___XXXXX,
  XXXXXX_X, XX______, ________, ______XX, X_XXXXXX,
  XXXXXXXX, XX______, ________, ______XX, XXXXXXXX,
  XXXXXXXX, X_______, ________, _______X, XXXXXXXX,
  XXXXXX_X, X_______, ________, _______X, X_XXXXXX,
  XXXX___X, X_______, ________, _______X, X___XXXX,
  XX_____X, X_______, ________, _______X, X_____XX,
  X______X, ________, ________, _______X, X______X,
  XX_____X, X_______, ________, _______X, X_____XX,
  XXXX___X, X_______, ________, _______X, X___XXXX,
  XXXXXXXX, X_______, ________, _______X, XXXXXXXX,
  XXXXXXXX, X_______, ________, _______X, XXXXXXXX,
  XXXXXXXX, XX______, ________, ______XX, XXXXXXXX,
  XXXXXX_X, XX______, ________, ______XX, X_XXXXXX,
  XXXXXX__, XXX_____, ________, _____XXX, ___XXXXX,
  XXXXX___, _XXX____, ________, ____XXX_, ___XXXXX,
  XXXX____, _XXXX___, ________, ___XXXX_, ____XXXX,
  XXXX____, __XXXXX_, ________, _XXXXX__, ____XXXX,
  XXX____X, XXXXXXXX, XX____XX, XXXXXXXX, X____XXX,
  XXXXXXXX, XXXX__XX, XXXXXXXX, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _XXXXXX_, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, __XXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _XXXXXX_, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, XXXXXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX__X, XXXXXXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_XX, XXXXXXXX, XX_XXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmicon_outdoor = {
  40, // xSize
  37, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _acicon_outdoor,  // Pointer to picture data (indices)
  &_Palicon_outdoor   // Pointer to palette
};

/*************************** End of file ****************************/
