/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_internet                                         *
* Dimensions:  35 * 35                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_internet;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsicon_internet[] = {
#if (GUI_USE_ARGB == 0)
  0xFFFFFF, 0x000000
#else
  0xFFFFFFFF,0xFF000000
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palicon_internet = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsicon_internet[0]
};

static GUI_CONST_STORAGE unsigned char _acicon_internet[] = {
  XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXX_____,
  XXXXXXXX, XX______, ________, _XXXXXXX, XXX_____,
  XXXXXXXX, ________, ________, ___XXXXX, XXX_____,
  XXXXXXX_, _______X, ___X____, ____XXXX, XXX_____,
  XXXXXX__, _XX___XX, ___XX___, XX___XXX, XXX_____,
  XXXXX___, XXX__XXX, ___XXX__, XXX___XX, XXX_____,
  XXXX___X, XX___XXX, ___XXX__, _XXX___X, XXX_____,
  XXX___XX, XX__XXXX, ___XXXX_, _XXXX___, XXX_____,
  XX______, ________, ________, ________, _XX_____,
  XX______, ________, ________, ________, _XX_____,
  X___XXXX, X__XXXXX, ___XXXXX, __XXXXX_, __X_____,
  X__XXXXX, X__XXXXX, ___XXXXX, __XXXXXX, __X_____,
  X__XXXXX, X__XXXXX, ___XXXXX, __XXXXXX, __X_____,
  ___XXXXX, ___XXXXX, ___XXXXX, ___XXXXX, ________,
  __XXXXXX, __XXXXXX, ___XXXXX, X__XXXXX, X_______,
  __XXXXXX, __XXXXXX, ___XXXXX, X__XXXXX, X_______,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  __XXXXXX, __XXXXXX, ___XXXXX, X__XXXXX, X_______,
  __XXXXXX, __XXXXXX, ___XXXXX, X__XXXXX, X_______,
  ___XXXXX, ___XXXXX, ___XXXXX, ___XXXXX, ________,
  X__XXXXX, X__XXXXX, ___XXXXX, __XXXXXX, __X_____,
  X__XXXXX, X__XXXXX, ___XXXXX, __XXXXXX, __X_____,
  X___XXXX, X__XXXXX, ___XXXXX, __XXXXX_, __X_____,
  XX______, ________, ________, ________, _XX_____,
  XX______, ________, ________, ________, _XX_____,
  XXX___XX, XX__XXXX, ___XXXX_, _XXXX___, XXX_____,
  XXXX___X, XX___XXX, ___XXX__, _XXX___X, XXX_____,
  XXXXX___, XXX__XXX, ___XXX__, XXX___XX, XXX_____,
  XXXXXX__, _XX___XX, ___XX___, XX___XXX, XXX_____,
  XXXXXXX_, _______X, ___X____, ____XXXX, XXX_____,
  XXXXXXXX, ________, ________, ___XXXXX, XXX_____,
  XXXXXXXX, XX______, ________, _XXXXXXX, XXX_____,
  XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmicon_internet = {
  35, // xSize
  35, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _acicon_internet,  // Pointer to picture data (indices)
  &_Palicon_internet   // Pointer to palette
};

/*************************** End of file ****************************/
