/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "cmsis_compiler.h"
#include <stdio.h>
#include "ui.h"
#include "main.h"
#include "rtc.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW                   (GUI_ID_USER + 0x0C)
#define ID_TIME_HOUR                (GUI_ID_USER + 0x0D)
#define ID_TIME_MIN                 (GUI_ID_USER + 0x2D)
#define ID_DOT                      (GUI_ID_USER + 0x1D)
#define ID_TEMPERATURE              (GUI_ID_USER + 0x0E)
#define ID_HUMIDITY                 (GUI_ID_USER + 0x0F)
#define ID_HEADER_0                 (GUI_ID_USER + 0x10)
#define ID_HEADER_1                 (GUI_ID_USER + 0x11)

WM_HWIN hWin;

// USER START (Optionally insert additional defines)
// USER END
uint32_t enable_setting = 0;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW, -2, -2, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "00", ID_TIME_HOUR, 30, 100, 770, 220, 0, 0x66, 0 },  
  { TEXT_CreateIndirect, "00", ID_TIME_MIN, 430, 100, 770, 220, 0, 0x66, 0 },   
  { TEXT_CreateIndirect, ":", ID_DOT, 370, 100, 120, 220, 0, 0x66, 0 },    
  { TEXT_CreateIndirect, "00.0 °C", ID_TEMPERATURE, 20, 360, 720, 120, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "00 %", ID_HUMIDITY, 480, 360, 680, 120, 0, 0x65, 0 },
  { HEADER_CreateIndirect, "Header", ID_HEADER_0, 20, 300, 760, 5, 0, 0x0, 0 },  
  { HEADER_CreateIndirect, "Header", ID_HEADER_1, 20, 40, 760, 5, 0, 0x0, 0 },    

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
#define RERESH_TIME 200
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDigital_Font;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDigita_Clock;
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  static WM_HTIMER   hTimer;  
  static WM_HTIMER   mTimer;    
  int Id, Node;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:

    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEMPERATURE);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x008080FF));
    TEXT_SetFont(hItem, &GUI_FontDigital_Font);
    TEXT_SetText(hItem, "--.- °C");
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_HUMIDITY);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FFFF));
    TEXT_SetFont(hItem, &GUI_FontDigital_Font);
    TEXT_SetText(hItem, "-- %");
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TIME_HOUR);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFF00));
    TEXT_SetFont(hItem, &GUI_FontDigita_Clock);
    TEXT_SetText(hItem, "00");
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TIME_MIN);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFF00));
    TEXT_SetFont(hItem, &GUI_FontDigita_Clock);
    TEXT_SetText(hItem, "00");      
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DOT);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFF00));
    TEXT_SetFont(hItem, &GUI_FontDigita_Clock);
    TEXT_SetText(hItem, ":");       
    
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;

  case WM_TIMER:
    RTC_TimeTypeDef Time;  
    RTC_DateTypeDef Date;      
    WM_RestartTimer(pMsg->Data.v, RERESH_TIME);
    Id = WM_GetTimerId(pMsg->Data.v);
    
    k_GetTime(&Time) ; 
    k_GetDate(&Date) ;            
    if(Id == 0) //hour
    {        
      Time.Hours++;
      
      if(Time.Hours >= 24)
      {
        Time.Hours = 0;
      }        
      k_SetTime(&Time) ; 
      UI_SetTime(Time.Hours, Time.Minutes, Time.Seconds);
    }
    else if(Id == 1) //min
    {
      Time.Minutes++;
      if(Time.Minutes >= 60)
      {
        Time.Minutes = 0;
        Time.Seconds = 0;          
      }
      
      k_SetTime(&Time) ; 
      UI_SetTime(Time.Hours, Time.Minutes, Time.Seconds);
    }      
    
    break;  
      
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);     
    Node = pMsg->Data.v;  

    
    if(Node == WM_NOTIFICATION_CLICKED)
    {
      
      Id    = WM_GetId(pMsg->hWinSrc);    /* Id of widget */
      if((Id == ID_TIME_HOUR) && (enable_setting))
      {
        if(!hTimer) hTimer = WM_CreateTimer(pMsg->hWin, 0, RERESH_TIME, 0);         
      }
      if((Id == ID_TIME_MIN) && (enable_setting))
      {
        if(!mTimer) mTimer = WM_CreateTimer(pMsg->hWin, 1, RERESH_TIME, 0);           
      }      
    }
    
    if(Node == WM_NOTIFICATION_RELEASED)
    {
      
      Id    = WM_GetId(pMsg->hWinSrc);    /* Id of widget */
      if((Id == ID_TIME_HOUR) && (enable_setting))
      {
        WM_DeleteTimer(hTimer); 
        hTimer = 0;
      }
      if((Id == ID_TIME_MIN) && (enable_setting))
      {
        WM_DeleteTimer(mTimer); 
        mTimer = 0;
      }      
    }
    break;
    
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

void UI_SetTemperature(uint32_t Temperature_int, uint32_t Temeparture_dec)
{
    WM_HWIN hItem;
    char temp[10];
    hItem = WM_GetDialogItem(hWin, ID_TEMPERATURE);
    snprintf(temp, sizeof(temp), "%d.%d C", Temperature_int, Temeparture_dec);
    TEXT_SetText(hItem, temp);      
}

void UI_SetHumidity(uint32_t Humidity_int, uint32_t Humidity_dec)
{
    WM_HWIN hItem;
    char temp[10];
    hItem = WM_GetDialogItem(hWin, ID_HUMIDITY);
    snprintf(temp, sizeof(temp), "%d %%", Humidity_int);
    TEXT_SetText(hItem, temp);      
}

void UI_SetTime(uint32_t hour, uint32_t min, uint32_t sec)
{
  WM_HWIN hItem;
  char temp[20];
  static uint32_t toggle =0;
  
  hItem = WM_GetDialogItem(hWin, ID_TIME_HOUR);
  
  snprintf(temp, sizeof(temp), "%02d", hour);
  
  TEXT_SetText(hItem, temp);      
  
  hItem = WM_GetDialogItem(hWin, ID_TIME_MIN);
  
  snprintf(temp, sizeof(temp), "%02d", min);
  
  TEXT_SetText(hItem, temp);     
  
  hItem = WM_GetDialogItem(hWin, ID_DOT); 
  toggle = 1- toggle;
  
  if(toggle)
  TEXT_SetText(hItem, ":");       
  else
  TEXT_SetText(hItem, " ");      
    
}

void ui_set_setting_mode (uint32_t enable)
{
  WM_HWIN hItem;  
  enable_setting = enable;
  
  if(enable)
  {
    hItem = WM_GetDialogItem(hWin, ID_TIME_HOUR);
    TEXT_SetTextColor(hItem, GUI_ORANGE);
    hItem = WM_GetDialogItem(hWin, ID_TIME_MIN);
    TEXT_SetTextColor(hItem, GUI_ORANGE);
    hItem = WM_GetDialogItem(hWin, ID_DOT);
    TEXT_SetTextColor(hItem, GUI_ORANGE);    
  }
  else
  {
    hItem = WM_GetDialogItem(hWin, ID_TIME_HOUR);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFF00));
    hItem = WM_GetDialogItem(hWin, ID_TIME_MIN);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFF00));
    hItem = WM_GetDialogItem(hWin, ID_DOT);
    TEXT_SetTextColor(hItem, 0x00FFFF00);     
  }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {


  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
