/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DigitGraphics20.c                                     *
* Font:        01 DigitGraphics                                      *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDigitGraphics20;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0021[ 15] = { /* code 0021, EXCLAMATION MARK */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0022[  6] = { /* code 0022, QUOTATION MARK */
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0023[ 30] = { /* code 0023, NUMBER SIGN */
  ___XXX__,XXX_____,
  ___XXX__,XXX_____,
  ___XXX__,XXX_____,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  ___XXX__,XXX_____,
  ___XXX__,XXX_____,
  ___XXX__,XXX_____,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  ___XXX__,XXX_____,
  ___XXX__,XXX_____,
  ___XXX__,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0024[ 30] = { /* code 0024, DOLLAR SIGN */
  ______XX,X_______,
  ___XXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXX_,
  ______XX,X___XXX_,
  ______XX,X___XXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0025[ 30] = { /* code 0025, PERCENT SIGN */
  ________,____XX__,
  __XX____,___XXX__,
  _XXXX___,__XXXX__,
  _XXXX___,_XXXX___,
  __XX____,XXXX____,
  _______X,XXX_____,
  ______XX,XX______,
  _____XXX,X_______,
  ____XXXX,________,
  ___XXXX_,________,
  __XXXX__,__XX____,
  _XXXX___,_XXXX___,
  XXXX____,_XXXX___,
  XXX_____,__XX____,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0026[ 26] = { /* code 0026, AMPERSAND */
  __XXXXXX,X_______,
  XXXXXXXX,XX______,
  XX______,XX______,
  XX______,_X______,
  XXX_____,________,
  XXXX____,________,
  _XXXXX__,________,
  XXXXXXX_,__XX____,
  XXX_XXXX,X_XX____,
  XX____XX,XXXX____,
  XX_____X,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0027[  6] = { /* code 0027, APOSTROPHE */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0028[ 15] = { /* code 0028, LEFT PARENTHESIS */
  ___XX___,
  _XXXX___,
  XXXX____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXXX____,
  _XXXX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0029[ 15] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  XXXX____,
  _XXXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XXXX___,
  XXXX____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_002A[ 30] = { /* code 002A, ASTERISK */
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  XXX___XX,X____XX_,
  _XXXX_XX,X__XXXX_,
  __XXXXXX,XXXXXX__,
  ____XXXX,XXXX____,
  _____XXX,XX______,
  ___XXXXX,XXX_____,
  _XXXXXXX,XXXXX___,
  XXXX__XX,X_XXXX__,
  XX____XX,X___XXX_,
  ______XX,X____X__,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_002B[ 30] = { /* code 002B, PLUS SIGN */
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_002C[  5] = { /* code 002C, COMMA */
  __XX____,
  _XXX____,
  XXXX____,
  XXX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_002D[  4] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_002E[  4] = { /* code 002E, FULL STOP */
  _XX_____,
  XXXX____,
  XXXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_002F[ 26] = { /* code 002F, SOLIDUS */
  ________,__XX____,
  ________,_XXX____,
  ________,XXXX____,
  _______X,XXX_____,
  ______XX,XX______,
  ______XX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  XXX_____,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0030[ 30] = { /* code 0030, DIGIT ZERO */
  ___XXXXX,XXXXX___,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  XXXX____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,__XXXXXX,
  XXX_____,XXXXXXXX,
  XXX___XX,XXX__XXX,
  XXX_XXXX,_____XXX,
  XXXXXX__,_____XXX,
  XXXX____,_____XXX,
  XXXX____,____XXXX,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  ___XXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0031[ 30] = { /* code 0031, DIGIT ONE */
  ____XXX_,________,
  ___XXXX_,________,
  __XXXXX_,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0032[ 30] = { /* code 0032, DIGIT TWO */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  ________,___XXX__,
  ________,____XX__,
  ________,___XXX__,
  __XXXXXX,XXXXXX__,
  _XXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  XXX_____,________,
  XX______,________,
  XXX_____,________,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0033[ 30] = { /* code 0033, DIGIT THREE */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  ________,___XXXX_,
  ________,____XXX_,
  ________,____XXX_,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  ________,____XXX_,
  ________,____XXX_,
  ________,___XXXX_,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0034[ 30] = { /* code 0034, DIGIT FOUR */
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXXX____,_XXX____,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXX_,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0035[ 30] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXX_,
  ________,____XXX_,
  ________,____XXX_,
  ________,____XXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0036[ 30] = { /* code 0036, DIGIT SIX */
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXX____,____XXX_,
  XXX_____,____XXX_,
  XXX_____,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXX_,
  XXX_____,____XXX_,
  XXX_____,____XXX_,
  XXXX____,____XXX_,
  XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0037[ 30] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  ________,___XXX__,
  ________,____XX__,
  ________,XXXXXX__,
  _______X,XXXXX___,
  ______XX,XXXX____,
  ______XX,X_______,
  ______XX,________,
  _____XXX,________,
  _____XXX,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0038[ 30] = { /* code 0038, DIGIT EIGHT */
  ___XXXXX,XXXXX___,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  XXXX____,____XXXX,
  XXX_____,_____XXX,
  XXXX____,____XXXX,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  XXXX____,____XXXX,
  XXX_____,_____XXX,
  XXXX____,____XXXX,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  ___XXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0039[ 30] = { /* code 0039, DIGIT NINE */
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXX_____,___XXXX_,
  XX______,____XXX_,
  XXX_____,____XXX_,
  XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  ________,____XXX_,
  XX______,____XXX_,
  XXX_____,___XXXX_,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_003A[ 10] = { /* code 003A, COLON */
  _X______,
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  _X______,
  XXX_____,
  XXX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_003B[ 11] = { /* code 003B, SEMICOLON */
  __XX____,
  _XXXX___,
  _XXXX___,
  __XX____,
  ________,
  ________,
  ________,
  __XXX___,
  _XXXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_003C[ 10] = { /* code 003C, LESS-THAN SIGN */
  ____XX__,
  ___XXX__,
  __XXXX__,
  _XXXX___,
  XXXX____,
  XXXX____,
  _XXXX___,
  __XXXX__,
  ___XXX__,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_003D[  9] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  ________,
  ________,
  ________,
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_003E[ 10] = { /* code 003E, GREATER-THAN SIGN */
  XX______,
  XXX_____,
  XXXX____,
  _XXXXX__,
  __XXXX__,
  __XXXX__,
  _XXXX___,
  XXXX____,
  XXX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_003F[ 30] = { /* code 003F, QUESTION MARK */
  ___XXXXX,XXXXX___,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,
  XXXX____,_____XXX,
  XXX_____,_____XXX,
  XXX_____,_____XXX,
  _X______,____XXXX,
  _______X,XXXXXXX_,
  _______X,XXXXXX__,
  _______X,XXXXX___,
  ________,________,
  _______X,X_______,
  ______XX,XX______,
  ______XX,XX______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0040[ 30] = { /* code 0040, COMMERCIAL AT */
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  XX______,___XXX__,
  X____XXX,XX__XX__,
  X___XXXX,XX__XX__,
  X__XXX_X,XX__XX__,
  X__XX__X,XX__XX__,
  X__XXX_X,XX_XXX__,
  X__XXXXX,XXXXXX__,
  X___XXXX,XXXXX___,
  XX___XXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0041[ 30] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____XXXX,XXX_____,
  ___XXXXX,XXX_____,
  ___XX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,__XX____,
  __XX____,__XX____,
  __XX____,__XXX___,
  _XXXXXXX,XXXXX___,
  _XXXXXXX,XXXXX___,
  _XXXXXXX,XXXXX___,
  XXX_____,___XXX__,
  XXX_____,___XXX__,
  XX______,____XX__,
  XX______,____XX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0042[ 30] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  XX______,___XXX__,
  XX______,___XXX__,
  XX______,___XXX__,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  XX______,___XXX__,
  XX______,___XXX__,
  XX______,___XXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0043[ 28] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXXX___,
  XXX_____,___XXX__,
  XX______,____XX__,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,____XX__,
  XXX_____,___XXX__,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0044[ 30] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXX__,
  __XXX___,___XXX__,
  __XXX___,____XX__,
  __XXX___,____XX__,
  __XXX___,____XX__,
  __XXX___,____XX__,
  __XXX___,____XX__,
  __XXX___,____XX__,
  __XXX___,____XX__,
  __XXX___,____XX__,
  __XXX___,___XXX__,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0045[ 28] = { /* code 0045, LATIN CAPITAL LETTER E */
  __XXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  XXX_____,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XX______,________,
  XX______,________,
  XXX_____,________,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0046[ 30] = { /* code 0046, LATIN CAPITAL LETTER F */
  __XXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXX_____,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0047[ 28] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXXX___,
  _XXX____,____XX__,
  XXX_____,____XX__,
  XXX_____,____XX__,
  XXX_____,________,
  XXX___XX,XXXXXX__,
  XXX__XXX,XXXXXX__,
  XXX___XX,XXXXXX__,
  XXX_____,____XX__,
  XXX_____,____XX__,
  XXXX____,____XX__,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0048[ 30] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0049[ 15] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_004A[ 28] = { /* code 004A, LATIN CAPITAL LETTER J */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  XX______,__XXX___,
  XX______,__XXX___,
  XX______,__XXX___,
  XXX_____,_XXXX___,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_004B[ 30] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX______,__XXXX__,
  XX______,XXXXXX__,
  XX____XX,XXXXXX__,
  XX___XXX,XX______,
  XX_XXXXX,X_______,
  XXXXXXX_,________,
  XXXXXXX_,________,
  XXXX_XXX,________,
  XX___XXX,X_______,
  XX____XX,X_______,
  XX_____X,XX______,
  XX______,XXX_____,
  XX______,XXXX____,
  XX______,_XXXXX__,
  XX______,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_004C[ 30] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXX_____,________,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_004D[ 42] = { /* code 004D, LATIN CAPITAL LETTER M */
  __XXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,X_______,
  XXXX____,XXX____X,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,XXX_____,XX______,
  XXX_____,________,XX______,
  XXX_____,________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_004E[ 30] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XX______,___XXX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_004F[ 28] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXXX___,
  XXX_____,___XXX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XXX_____,___XXX__,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0050[ 30] = { /* code 0050, LATIN CAPITAL LETTER P */
  _XXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XX______,___XXX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,___XXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0051[ 28] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXXXXX,XXXXX___,
  _XXXXXXX,XXXXXX__,
  XXX_____,___XXXX_,
  XX______,____XXX_,
  XX______,____XXX_,
  XX____XX,X___XXX_,
  XX____XX,XX__XXX_,
  XX____XX,XXX_XXX_,
  XX______,XXXXXXX_,
  XX______,_XXXXXX_,
  XXX_____,__XXXXX_,
  XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0052[ 30] = { /* code 0052, LATIN CAPITAL LETTER R */
  _XXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XX______,___XXX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,___XXX__,
  XX______,___XXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  XX______,XXXX____,
  XX______,_XXXX___,
  XX______,__XXXX__,
  XX______,___XXX__,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0053[ 28] = { /* code 0053, LATIN CAPITAL LETTER S */
  ___XXXXX,XXXXX___,
  _XXXXXXX,XXXXXX__,
  _XXX____,____XXX_,
  XXX_____,_____XX_,
  XXX_____,________,
  _XXX____,________,
  _XXXXXXX,XXXXX___,
  ___XXXXX,XXXXXX__,
  ________,____XXX_,
  ________,____XXX_,
  _X______,____XXX_,
  XXX_____,____XXX_,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0054[ 28] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0055[ 30] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XXX_____,___XXX__,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0056[ 28] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,____XX__,
  XX______,____XX__,
  XXX_____,___XXX__,
  XXX_____,___XXX__,
  _XX_____,___XX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  __XX____,__XX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,_XX_____,
  ___XXX__,XXX_____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0057[ 42] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX______,_______X,XX______,
  XX______,_______X,XX______,
  XX_____X,XX_____X,XX______,
  XX_____X,XX_____X,XX______,
  XX_____X,XX_____X,XX______,
  XX_____X,XX_____X,XX______,
  XX_____X,XX_____X,XX______,
  XX_____X,XX_____X,XX______,
  XX_____X,XX_____X,XX______,
  XX_____X,XX_____X,XX______,
  XX_____X,XX_____X,XX______,
  XXX____X,XX____XX,XX______,
  _XXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0058[ 28] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXX____,__XXXXX_,
  XXXXX___,__XXXXX_,
  _XXXXX__,_XXX____,
  ___XXX__,XXX_____,
  ____XXXX,XXX_____,
  _____XXX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,XX______,
  ____XXX_,XX______,
  ___XXX__,XXX_____,
  ___XX___,_XXX____,
  XXXXX___,__XXXXX_,
  XXXX____,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0059[ 30] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,____X___,
  XX______,___XXX__,
  XX______,___XXX__,
  XX______,___XXX__,
  XX______,___XXX__,
  XX______,___XXX__,
  XXX_____,__XXXX__,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_005A[ 30] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  ________,___XXX__,
  ________,__XXX___,
  ________,XXXX____,
  _______X,XXX_____,
  _____XXX,X_______,
  ____XXXX,________,
  ___XXX__,________,
  _XXXX___,________,
  XXX_____,________,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_005B[ 15] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_005C[ 26] = { /* code 005C, REVERSE SOLIDUS */
  XX______,________,
  XXX_____,________,
  _XXX____,________,
  __XXX___,________,
  ___XXX__,________,
  ____XXX_,________,
  _____XXX,________,
  ______XX,X_______,
  _______X,XX______,
  ________,XXX_____,
  ________,_XXX____,
  ________,__XX____,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_005D[ 15] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_005E[ 14] = { /* code 005E, CIRCUMFLEX ACCENT */
  ____XX__,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXXXXXX,X_______,
  XXXX__XX,XX______,
  XXX____X,XXX_____,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_005F[  6] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0060[  5] = { /* code 0060, GRAVE ACCENT */
  XX______,
  XXX_____,
  XXXX____,
  _XXXX___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0061[ 18] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XX______,__XX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0062[ 26] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XX______,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0063[ 18] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXXXX,XX______,
  _XXXXXXX,XXXX____,
  XXX_____,__XXX___,
  XX______,___X____,
  XX______,________,
  XX______,___X____,
  XXX_____,__XXX___,
  _XXXXXXX,XXXX____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0064[ 26] = { /* code 0064, LATIN SMALL LETTER D */
  ________,__XX____,
  ________,__XX____,
  ________,__XX____,
  ________,__XX____,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  XXX_____,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0065[ 18] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XX______,__XX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XX______,________,
  XXX_____,__XX____,
  XXXXXXXX,XXXX____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0066[ 26] = { /* code 0066, LATIN SMALL LETTER F */
  _____XXX,XX______,
  ____XXXX,XX______,
  ___XXX__,________,
  ___XX___,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0067[ 24] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  XXX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ________,_XXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0068[ 26] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0069[ 13] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XXX_____,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  ____XX__,
  ___XXX__,
  ____XX__,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_006B[ 26] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,XXXX____,
  XX___XXX,XXXX____,
  XX_XXXXX,________,
  XXXXXX__,________,
  XX__XXX_,________,
  XX___XXX,________,
  XX____XX,X_______,
  XX_____X,XXXX____,
  XX______,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_006C[ 13] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XXX_____,
  _XXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,
  XX_____X,X_____XX,
  XX_____X,X_____XX,
  XX_____X,X_____XX,
  XX_____X,X_____XX,
  XX_____X,X_____XX,
  XX_____X,X_____XX,
  XX_____X,X_____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_006E[ 18] = { /* code 006E, LATIN SMALL LETTER N */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_006F[ 18] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  XXX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0070[ 24] = { /* code 0070, LATIN SMALL LETTER P */
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  XXX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0071[ 24] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  XXX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ________,__XX____,
  ________,__XX____,
  ________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0072[ 20] = { /* code 0072, LATIN SMALL LETTER R */
  X_______,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XX______,__XXX___,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0073[ 18] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XX______,__XX____,
  XXXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  X_______,__XX____,
  XXX_____,_XXX____,
  XXXXXXXX,XXXX____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0074[ 26] = { /* code 0074, LATIN SMALL LETTER T */
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XXX__,________,
  ____XXXX,XX______,
  _____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0075[ 20] = { /* code 0075, LATIN SMALL LETTER U */
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0076[ 18] = { /* code 0076, LATIN SMALL LETTER V */
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  __XX____,XX______,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XXX___XX,___XXX__,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0078[ 18] = { /* code 0078, LATIN SMALL LETTER X */
  XXX_____,_XXX____,
  XXXX____,XXXX____,
  __XXX__X,XX______,
  ___XXXXX,X_______,
  ____XXXX,________,
  ___XXXXX,X_______,
  ___XX__X,XX______,
  XXXX____,XXXX____,
  XXX_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_0079[ 24] = { /* code 0079, LATIN SMALL LETTER Y */
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_007A[ 18] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  ________,_XXX____,
  ______XX,XXXX____,
  __XXXXXX,XX______,
  XXXXXXX_,________,
  XXX_____,________,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_007E[  8] = { /* code 007E, TILDE */
  _XXXXXX_,__XXX___,
  XXXXXXXX,_XXXX___,
  XXX__XXX,XXXX____,
  XX____XX,XXX_____};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_00A0[  1] = { /* code 00A0, NO-BREAK SPACE */
  ________};

/* Start of unicode area <Special> */
GUI_CONST_STORAGE unsigned char acGUI_FontDigitGraphics20_FFFF[ 32] = { /* code FFFF */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDigitGraphics20_CharInfo[94] = {
   {   1,   1,   0,  16,   6, acGUI_FontDigitGraphics20_0020 } /* code 0020, SPACE */
  ,{   3,  15,   1,   1,   5, acGUI_FontDigitGraphics20_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   8,   6,   1,   2,  11, acGUI_FontDigitGraphics20_0022 } /* code 0022, QUOTATION MARK */
  ,{  14,  15,   2,   1,  17, acGUI_FontDigitGraphics20_0023 } /* code 0023, NUMBER SIGN */
  ,{  15,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0024 } /* code 0024, DOLLAR SIGN */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0025 } /* code 0025, PERCENT SIGN */
  ,{  13,  13,   2,   3,  15, acGUI_FontDigitGraphics20_0026 } /* code 0026, AMPERSAND */
  ,{   3,   6,   1,   2,   5, acGUI_FontDigitGraphics20_0027 } /* code 0027, APOSTROPHE */
  ,{   5,  15,   1,   1,   7, acGUI_FontDigitGraphics20_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   5,  15,   1,   1,   7, acGUI_FontDigitGraphics20_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{  15,  15,   1,   1,  16, acGUI_FontDigitGraphics20_002A } /* code 002A, ASTERISK */
  ,{  15,  15,   2,   1,  16, acGUI_FontDigitGraphics20_002B } /* code 002B, PLUS SIGN */
  ,{   5,   5,   2,  12,   6, acGUI_FontDigitGraphics20_002C } /* code 002C, COMMA */
  ,{   9,   2,   2,   9,  11, acGUI_FontDigitGraphics20_002D } /* code 002D, HYPHEN-MINUS */
  ,{   4,   4,   1,  11,   5, acGUI_FontDigitGraphics20_002E } /* code 002E, FULL STOP */
  ,{  12,  13,   2,   3,  15, acGUI_FontDigitGraphics20_002F } /* code 002F, SOLIDUS */
  ,{  16,  15,   1,   1,  16, acGUI_FontDigitGraphics20_0030 } /* code 0030, DIGIT ZERO */
  ,{  11,  15,   1,   1,  12, acGUI_FontDigitGraphics20_0031 } /* code 0031, DIGIT ONE */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0032 } /* code 0032, DIGIT TWO */
  ,{  15,  15,   2,   1,  17, acGUI_FontDigitGraphics20_0033 } /* code 0033, DIGIT THREE */
  ,{  16,  15,   1,   1,  16, acGUI_FontDigitGraphics20_0034 } /* code 0034, DIGIT FOUR */
  ,{  15,  15,   1,   1,  16, acGUI_FontDigitGraphics20_0035 } /* code 0035, DIGIT FIVE */
  ,{  15,  15,   1,   1,  16, acGUI_FontDigitGraphics20_0036 } /* code 0036, DIGIT SIX */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0037 } /* code 0037, DIGIT SEVEN */
  ,{  16,  15,   1,   1,  16, acGUI_FontDigitGraphics20_0038 } /* code 0038, DIGIT EIGHT */
  ,{  15,  15,   2,   1,  17, acGUI_FontDigitGraphics20_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  10,   2,   4,   5, acGUI_FontDigitGraphics20_003A } /* code 003A, COLON */
  ,{   5,  11,   2,   4,   5, acGUI_FontDigitGraphics20_003B } /* code 003B, SEMICOLON */
  ,{   7,  10,   2,   4,  11, acGUI_FontDigitGraphics20_003C } /* code 003C, LESS-THAN SIGN */
  ,{   8,   9,   2,   5,  11, acGUI_FontDigitGraphics20_003D } /* code 003D, EQUALS SIGN */
  ,{   7,  10,   2,   4,  11, acGUI_FontDigitGraphics20_003E } /* code 003E, GREATER-THAN SIGN */
  ,{  16,  15,   1,   1,  16, acGUI_FontDigitGraphics20_003F } /* code 003F, QUESTION MARK */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0040 } /* code 0040, COMMERCIAL AT */
  ,{  14,  15,   2,   2,  16, acGUI_FontDigitGraphics20_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  14,  14,   2,   2,  16, acGUI_FontDigitGraphics20_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  14,  14,   2,   2,  16, acGUI_FontDigitGraphics20_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  14,  14,   2,   2,  16, acGUI_FontDigitGraphics20_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  15,   2,   1,   4, acGUI_FontDigitGraphics20_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  15,  14,   2,   2,  17, acGUI_FontDigitGraphics20_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  18,  14,   1,   2,  20, acGUI_FontDigitGraphics20_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  14,  14,   2,   2,  16, acGUI_FontDigitGraphics20_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  14,  15,   2,   2,  16, acGUI_FontDigitGraphics20_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  15,  14,   2,   2,  17, acGUI_FontDigitGraphics20_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  15,  15,   2,   2,  16, acGUI_FontDigitGraphics20_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  15,  14,   2,   2,  17, acGUI_FontDigitGraphics20_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  15,  14,   2,   2,  16, acGUI_FontDigitGraphics20_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  14,  15,   2,   1,  16, acGUI_FontDigitGraphics20_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  14,  14,   2,   2,  16, acGUI_FontDigitGraphics20_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  18,  14,   2,   2,  20, acGUI_FontDigitGraphics20_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  15,  14,   2,   2,  17, acGUI_FontDigitGraphics20_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  14,  15,   2,   1,  17, acGUI_FontDigitGraphics20_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  15,  15,   2,   1,  16, acGUI_FontDigitGraphics20_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   6,  15,   1,   1,   8, acGUI_FontDigitGraphics20_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{  12,  13,   2,   3,  14, acGUI_FontDigitGraphics20_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   6,  15,   1,   1,   8, acGUI_FontDigitGraphics20_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{  11,   7,   2,   2,  13, acGUI_FontDigitGraphics20_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{  14,   3,   2,  13,  15, acGUI_FontDigitGraphics20_005F } /* code 005F, LOW LINE */
  ,{   5,   5,   2,   5,   8, acGUI_FontDigitGraphics20_0060 } /* code 0060, GRAVE ACCENT */
  ,{  12,   9,   2,   7,  14, acGUI_FontDigitGraphics20_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  12,  13,   2,   3,  14, acGUI_FontDigitGraphics20_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{  13,   9,   2,   7,  14, acGUI_FontDigitGraphics20_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  12,  13,   2,   3,  14, acGUI_FontDigitGraphics20_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{  12,   9,   2,   7,  14, acGUI_FontDigitGraphics20_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{  10,  13,   2,   3,  11, acGUI_FontDigitGraphics20_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  12,  12,   2,   7,  14, acGUI_FontDigitGraphics20_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  12,  13,   2,   3,  14, acGUI_FontDigitGraphics20_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   3,  13,   2,   3,   4, acGUI_FontDigitGraphics20_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   6,  16,   2,   3,   9, acGUI_FontDigitGraphics20_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  13,  13,   2,   3,  14, acGUI_FontDigitGraphics20_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   4,  13,   2,   3,   6, acGUI_FontDigitGraphics20_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  16,   9,   2,   7,  18, acGUI_FontDigitGraphics20_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  12,   9,   2,   7,  14, acGUI_FontDigitGraphics20_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  12,   9,   2,   7,  14, acGUI_FontDigitGraphics20_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  12,  12,   2,   7,  14, acGUI_FontDigitGraphics20_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  12,  12,   2,   7,  14, acGUI_FontDigitGraphics20_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{  13,  10,   2,   6,  14, acGUI_FontDigitGraphics20_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{  13,   9,   2,   7,  14, acGUI_FontDigitGraphics20_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{  10,  13,   2,   3,  12, acGUI_FontDigitGraphics20_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  12,  10,   2,   6,  14, acGUI_FontDigitGraphics20_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  12,   9,   2,   7,  14, acGUI_FontDigitGraphics20_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  14,   9,   2,   7,  16, acGUI_FontDigitGraphics20_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  12,   9,   2,   7,  14, acGUI_FontDigitGraphics20_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  12,  12,   2,   7,  14, acGUI_FontDigitGraphics20_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{  12,   9,   2,   7,  14, acGUI_FontDigitGraphics20_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{  13,   4,   2,   4,  14, acGUI_FontDigitGraphics20_007E } /* code 007E, TILDE */
  ,{   1,   1,   0,  16,   8, acGUI_FontDigitGraphics20_00A0 } /* code 00A0, NO-BREAK SPACE */
  ,{  11,  16,   1,   0,  14, acGUI_FontDigitGraphics20_FFFF } /* code FFFF */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDigitGraphics20_Prop4 = {
   0xFFFF /* first character */
  ,0xFFFF /* last character  */
  ,&GUI_FontDigitGraphics20_CharInfo[ 93] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDigitGraphics20_Prop3 = {
   0x00A0 /* first character */
  ,0x00A0 /* last character  */
  ,&GUI_FontDigitGraphics20_CharInfo[ 92] /* address of first character */
  ,&GUI_FontDigitGraphics20_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDigitGraphics20_Prop2 = {
   0x007E /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontDigitGraphics20_CharInfo[ 91] /* address of first character */
  ,&GUI_FontDigitGraphics20_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDigitGraphics20_Prop1 = {
   0x0020 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontDigitGraphics20_CharInfo[  0] /* address of first character */
  ,&GUI_FontDigitGraphics20_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDigitGraphics20 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDigitGraphics20_Prop1}
  ,16 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

