/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_indoor                                           *
* Dimensions:  40 * 40                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_indoor;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsicon_indoor[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palicon_indoor = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsicon_indoor[0]
};

static GUI_CONST_STORAGE unsigned char _acicon_indoor[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, ________, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, ________, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, ________, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, ____XXXX, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, ____XXXX, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX____XX, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX____XX, ____XXXX, ________, XXXXXXXX,
  XXXXXXXX, XX____XX, ____XXXX, ________, XXXXXXXX,
  XXXXXXXX, XX____XX, ____XXXX, ________, XXXXXXXX,
  XXXXXXXX, XX____XX, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX____XX, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX____XX, ____XXXX, ____XXXX, XXXXXXXX,
  XXXXXXXX, X_____XX, _____XXX, _____XXX, XXXXXXXX,
  XXXXXXXX, ______XX, ______XX, ____XXXX, XXXXXXXX,
  XXXXXXX_, _____XXX, X______X, XXXXXXXX, XXXXXXXX,
  XXXXXXX_, ____XXXX, XX_____X, XXXXXXXX, XXXXXXXX,
  XXXXXX__, ___XXXXX, XXX_____, XXXXXXXX, XXXXXXXX,
  XXXXXX__, __XXXXXX, XXXX____, XXXXXXXX, XXXXXXXX,
  XXXXXX__, __XXXXXX, XXXX____, XXXXXXXX, XXXXXXXX,
  XXXXXX__, __XXXXXX, XXXX____, XXXXXXXX, XXXXXXXX,
  XXXXXX__, ___XXXXX, XXX_____, XXXXXXXX, XXXXXXXX,
  XXXXXX__, ___XXXXX, XXX_____, XXXXXXXX, XXXXXXXX,
  XXXXXXX_, ____XXXX, XX_____X, XXXXXXXX, XXXXXXXX,
  XXXXXXX_, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, ________, ______XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_______, _____XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmicon_indoor = {
  40, // xSize
  40, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _acicon_indoor,  // Pointer to picture data (indices)
  &_Palicon_indoor   // Pointer to palette
};

/*************************** End of file ****************************/
