/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_wifi                                             *
* Dimensions:  40 * 28                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_wifi;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsicon_wifi[] = {
#if (GUI_USE_ARGB == 0)
  0xCECECE, 0x000000
#else
  0xFFCECECE,0xFF000000
#endif
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palicon_wifi = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsicon_wifi[0]
};

#if defined ( __ICCARM__ )
#pragma location="ExtQSPIFlashSection" 
#else
__attribute__((section(".ExtQSPIFlashSection")))  
#endif
static GUI_CONST_STORAGE unsigned char _acicon_wifi[] = {
  XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XX______, ________, ______XX, XXXXXXXX,
  XXXXXXXX, ________, ________, ________, XXXXXXXX,
  XXXXXX__, ________, _XXXXX__, ________, _XXXXXXX,
  XXXXX___, _____XXX, XXXXXXXX, XX______, ___XXXXX,
  XXXX____, ___XXXXX, XXXXXXXX, XXXX____, ____XXXX,
  XX______, _XXXXXXX, XXXXXXXX, XXXXXX__, ______XX,
  X_______, XXXXXXXX, _______X, XXXXXXXX, _______X,
  _______X, XXXXX___, ________, __XXXXXX, X_______,
  X____XXX, XXX_____, ________, ____XXXX, XX_____X,
  XX__XXXX, X_______, ________, ______XX, XXXX__XX,
  XXXXXXXX, ________, _XXXXX__, _______X, XXXXXXXX,
  XXXXXXX_, ______XX, XXXXXXXX, X_______, _XXXXXXX,
  XXXXXX__, _____XXX, XXXXXXXX, XXX_____, __XXXXXX,
  XXXXXX__, ___XXXXX, XXXXXXXX, XXXX____, __XXXXXX,
  XXXXXXX_, __XXXXXX, _______X, XXXXXX__, _XXXXXXX,
  XXXXXXXX, _XXXXX__, ________, _XXXXXX_, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, _XXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, XXXXXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmicon_wifi = {
  40, // xSize
  28, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _acicon_wifi,  // Pointer to picture data (indices)
  &_Palicon_wifi   // Pointer to palette
};

/*************************** End of file ****************************/
