/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_indoor                                           *
* Dimensions:  50 * 40                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_indoor;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsicon_indoor[] = {
#if (GUI_USE_ARGB == 0)
  0xCECECE, 0x000000
#else
  0xFFCECECE, 0xFF000000
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palicon_indoor = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsicon_indoor[0]
};
#if defined ( __ICCARM__ )
#pragma location="ExtQSPIFlashSection" 
#else
__attribute__((section(".ExtQSPIFlashSection")))  
#endif
static GUI_CONST_STORAGE unsigned char _acicon_indoor[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXX____, ______XX, XX_____X, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXX_____, _______X, X______X, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, X_______, ________, X______X, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, ________, ________, _______X, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXX_, ________, ________, _______X, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXX__, ________, ________, _______X, XXXXXXXX, XX______,
  XXXXXXXX, XXXXX___, ________, ________, _______X, XXXXXXXX, XX______,
  XXXXXXXX, XXX_____, ________, ________, _______X, XXXXXXXX, XX______,
  XXXXXXXX, XX______, ______XX, XXX_____, _______X, XXXXXXXX, XX______,
  XXXXXXXX, X_______, _____XXX, XXXX____, ________, XXXXXXXX, XX______,
  XXXXXXXX, ________, _____XXX, __XXX___, ________, __XXXXXX, XX______,
  XXXXXXX_, ________, _____XXX, __XXX___, ________, ___XXXXX, XX______,
  XXXXXX__, ________, _____XXX, __XXX___, ________, ___XXXXX, XX______,
  XXXXXXX_, ________, _____XXX, __XXX___, ________, ___XXXXX, XX______,
  XXXXXXXX, XXXX____, _____XXX, __XXX___, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, _____XXX, X_XXX___, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, _____XXX, X_XXX___, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, _____XXX, X_XXX___, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, _____XXX, X_XXX___, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, _____XXX, X_XXX___, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, ____XXX_, XX_XXX__, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, ____XX_X, XXXXXX__, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, ____XX_X, XX_XXX__, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, ____XXXX, __XXX___, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, _____XXX, XXXXX___, ______XX, XXXXXXXX, XX______,
  XXXXXXXX, XXXX____, _______X, XXX_____, _____XXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______
};

GUI_CONST_STORAGE GUI_BITMAP bmicon_indoor = {
  50, // xSize
  40, // ySize
  7, // BytesPerLine
  1, // BitsPerPixel
  _acicon_indoor,  // Pointer to picture data (indices)
  &_Palicon_indoor   // Pointer to palette
};

/*************************** End of file ****************************/
