/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_wifi                                             *
* Dimensions:  55 * 40                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_wifi;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsicon_wifi[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palicon_wifi = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsicon_wifi[0]
};

static GUI_CONST_STORAGE unsigned char _acicon_wifi[] = {
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XX______, ________, ____XXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, ________, ________, _______X, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXX___, ________, ________, ________, _XXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXX____, ________, ________, ________, ___XXXXX, XXXXXXX_,
  XXXXXXXX, XX______, ________, ________, ________, _____XXX, XXXXXXX_,
  XXXXXXXX, ________, _______X, XXXXXXX_, ________, ______XX, XXXXXXX_,
  XXXXXXX_, ________, ____XXXX, XXXXXXXX, XXX_____, ________, XXXXXXX_,
  XXXXXX__, ________, _XXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXX_,
  XXXXX___, _______X, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, __XXXXX_,
  XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ___XXXX_,
  XX______, ____XXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXX_____, _____XX_,
  X_______, ___XXXXX, XXXX____, ________, __XXXXXX, XXXX____, ______X_,
  ________, _XXXXXXX, XX______, ________, ____XXXX, XXXXX___, ________,
  X_______, XXXXXXXX, ________, ________, ______XX, XXXXXXX_, ______X_,
  XX_____X, XXXXXX__, ________, ________, ________, XXXXXXXX, _____XX_,
  XXX___XX, XXXXX___, ________, ________, ________, _XXXXXXX, X___XXX_,
  XXXX_XXX, XXX_____, ________, ________, ________, ___XXXXX, XX_XXXX_,
  XXXXXXXX, XX______, ______XX, XXXXXXXX, ________, ____XXXX, XXXXXXX_,
  XXXXXXXX, X_______, ___XXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXX_,
  XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XXXX____, ______XX, XXXXXXX_,
  XXXXXXXX, ________, XXXXXXXX, XXXXXXXX, XXXXXX__, _______X, XXXXXXX_,
  XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXX_,
  XXXXXXXX, XX____XX, XXXXXX__, ________, XXXXXXXX, X____XXX, XXXXXXX_,
  XXXXXXXX, XXX__XXX, XXXX____, ________, __XXXXXX, XX__XXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XX______, ________, ___XXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, X_______, ________, _____XXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, ________, ________, ______XX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, ________, ________, ______XX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, X_______, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XX____XX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, X__XXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXXXXXXX, XXXXXXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmicon_wifi = {
  55, // xSize
  40, // ySize
  7, // BytesPerLine
  1, // BitsPerPixel
  _acicon_wifi,  // Pointer to picture data (indices)
  &_Palicon_wifi   // Pointer to palette
};

/*************************** End of file ****************************/
